-- Central de Implantação content (SM/LE stages, e-mail templates, modules), moved from
-- the static web/src/data/*.ts files into Supabase so the admin screen can edit them
-- without a redeploy. RLS is enabled with no policies: only server-side code using the
-- secret (service_role) key can read/write — the browser never touches this directly.

create table if not exists public.process_stages (
  segment text not null check (segment in ('sm', 'le')),
  id text not null,
  "order" int not null,
  title text not null,
  short_description text not null default '',
  owner text not null check (owner in ('consultor', 'gp', 'cliente', 'vendas', 'coordenacao')),
  participants text[] not null default '{}',
  sla text,
  content text[] not null default '{}',
  checklist text[] not null default '{}',
  warnings text[] not null default '{}',
  template_ids text[] not null default '{}',
  module_ids text[] not null default '{}',
  updated_at timestamptz not null default now(),
  primary key (segment, id)
);
alter table public.process_stages enable row level security;

create table if not exists public.process_templates (
  id text primary key,
  title text not null,
  url text,
  updated_at timestamptz not null default now()
);
alter table public.process_templates enable row level security;

create table if not exists public.process_modules (
  id text primary key,
  title text not null,
  content text[] not null default '{}',
  template_ids text[] not null default '{}',
  updated_at timestamptz not null default now()
);
alter table public.process_modules enable row level security;

-- set_updated_at() already exists from the profiles/review_sessions migration.
drop trigger if exists process_stages_set_updated_at on public.process_stages;
create trigger process_stages_set_updated_at before update on public.process_stages for each row execute function public.set_updated_at();
drop trigger if exists process_templates_set_updated_at on public.process_templates;
create trigger process_templates_set_updated_at before update on public.process_templates for each row execute function public.set_updated_at();
drop trigger if exists process_modules_set_updated_at on public.process_modules;
create trigger process_modules_set_updated_at before update on public.process_modules for each row execute function public.set_updated_at();

-- Seed data, auto-generated from web/src/data/*.ts — DO NOT hand-edit, regenerate instead.

insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'recebimento', 1, 'Recebimento do projeto', 'Entenda como o projeto chega até o time de Projetos e o que precisa ser verificado.', 'consultor', '{}', '2 dias úteis', ARRAY['O HubSpot é o CRM da empresa onde as informações ficam centralizadas e são repassadas entre os times. Quando o time de vendas finaliza uma venda, cria-se um ticket no HubSpot para que o cliente chegue ao time de implantação como um projeto vendido. O gestor da área é notificado e atribui o projeto a um consultor e a um gerente de projetos.','Somos notificados do início do projeto de duas formas: atribuição no ticket do HubSpot, e e-mail enviado pela gestão nos apresentando ao cliente.']::text[], ARRAY['Verificar a atribuição do projeto no ticket do HubSpot','Responder o e-mail de apresentação dentro do SLA']::text[], '{}', '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'analise-projeto', 2, 'Análise do projeto', 'Confira a proposta comercial e o histórico da venda antes do primeiro contato.', 'consultor', ARRAY['vendas']::text[], NULL, ARRAY['Proposta: analisar os módulos contratados (checar o check amarelo, exceto mobilidade — normalmente vem zerado na proposta); analisar as formas de pagamento do Travel; analisar se veio prazo de vigência na proposta.','HubSpot: verificar as propriedades preenchidas pelo vendas para entender o objetivo do cliente, e as observações do card para ver se o vendas deixou alguma informação relevante para a condução do projeto.','Repasse de vendas: reunião com o vendedor, para entender o histórico de venda do projeto.']::text[], ARRAY['Analisar os módulos contratados','Verificar formas de pagamento (Travel)','Analisar prazo de vigência','Verificar propriedades do HubSpot','Ler observações do card','Realizar repasse de vendas com o vendedor']::text[], ARRAY['Em caso de divergência na proposta, seguir o processo de devolutiva comercial formalizado.']::text[], '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'primeiro-contato', 3, 'Primeiro contato', 'Responda o cliente e solicite os requisitos de cada módulo contratado.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['Responder em cima do e-mail da coordenação, com o template "1. Template - Etapas de projeto SM - primeiro contato", sugerindo a agenda de kick off.','Solicitar os requisitos de cada módulo contratado com os e-mails padrão correspondentes.']::text[], '{}', '{}', ARRAY['tpl-primeiro-contato-sm','tpl-cargas-expense','tpl-requisitos-travel','tpl-implantacao-vcn','tpl-implantacao-cartao','tpl-carteira-digital']::text[], ARRAY['expense','travel','vcn','cartao-paytrack','carteira-digital']::text[]);
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'preparacao-interna', 4, 'Preparação interna', 'Monte o cronograma, a pasta do cliente e organize o HubSpot antes da primeira reunião.', 'consultor', ARRAY['gp','coordenacao']::text[], NULL, ARRAY['Criar o cronograma no Smartsheet assim que conseguir agendar o kick off.','Criar uma pasta para o cliente no Drive (na pasta de projetos), onde devem ser armazenadas todas as cargas, documentações e o escopo do projeto.','Mover o card no HubSpot para "Em andamento" após a reunião de kick off.']::text[], ARRAY['Time do projeto: preencher coordenador, consultor e GP','ID do HubSpot: obrigatório — é o que faz rodar a integração Smartsheet ↔ HubSpot','Potencial travel: preencher com o volume de viagens do HubSpot (campo "[TRVL] Soma de todos os potenciais de volume travel"); se vazio, preencher com zero e mapear o volume com o cliente depois','BU: conforme a segmentação do cliente no HubSpot — usado nos filtros do BI da gestão','Variância: ao criar um cronograma novo a partir do modelo, redefinir as "Referências iniciais" para não constar como atrasado','Tipo de projeto: Novo / Novo - Integração segunda onda / Base / Base - Segunda onda','Criar a pasta do cliente no Drive']::text[], ARRAY['O potencial travel é de suma importância para o time de viagens entender se precisa efetuar novas contratações.']::text[], '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'kick-off', 5, 'Kick-off', 'Conduza a reunião de abertura do projeto, com ou sem integração.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['Kick off com ou sem integração, conforme o escopo contratado.','Formalizar a reunião com o e-mail "2. Template Etapa 1 - Formalização - Kick-off".']::text[], '{}', '{}', ARRAY['tpl-kickoff-formalizacao']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'definicao-escopo', 6, 'Definição de escopo', 'Registre o escopo acordado e obtenha o aceite do cliente.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['Registrar todo o escopo no Termo de escopo e disponibilizá-lo para aceite na base de produção do cliente.','Enviar o e-mail "3. Template - Envio do Termo de escopo".']::text[], '{}', ARRAY['O aceite do escopo é obrigatório para seguir com a parametrização da base.']::text[], ARRAY['tpl-termo-escopo']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'parametrizacao', 7, 'Parametrização', 'Configure a base de acordo com o escopo aceito pelo cliente.', 'consultor', '{}', NULL, ARRAY['Parametrização da base conforme o escopo aceito pelo cliente.']::text[], '{}', '{}', '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'apresentacao-ferramenta', 8, 'Apresentação da ferramenta', 'Apresente a ferramenta parametrizada ao cliente.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['Apresentação da ferramenta já parametrizada ao cliente.']::text[], '{}', '{}', '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'homologacao-assistida', 9, 'Homologação assistida', 'Libere o acesso para o cliente testar a base.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['Liberar o acesso à base para o cliente efetuar os testes.','E-mail para liberar o acesso: "4. Template Etapa 3 - Homologação".']::text[], '{}', '{}', ARRAY['tpl-homologacao']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'retorno-testes', 10, 'Retorno dos testes', 'Receba e trate o retorno dos testes realizados pelo cliente.', 'cliente', ARRAY['consultor']::text[], NULL, ARRAY['Retorno dos testes realizados pelo cliente na base homologada.']::text[], '{}', '{}', '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'aceite-homologacao', 11, 'Aceite da homologação', 'Obtenha o aceite formal do Termo de homologação.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['O aceite do Termo de homologação é obrigatório para o go live do projeto.','E-mail a ser enviado: "2. Template Etapa 3 - Aceite da Homologação".']::text[], '{}', ARRAY['O aceite é obrigatório para o go live do projeto.']::text[], ARRAY['tpl-aceite-homologacao']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'treinamento-adm', 12, 'Treinamento de administrador', 'Treine o administrador da ferramenta no cliente.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['Treinamento de administrador.','E-mail: "4.1 Template Etapa 3 - Homologação (Treinamento ADM)".']::text[], '{}', '{}', ARRAY['tpl-treinamento-adm']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'treinamento-usuarios', 13, 'Treinamento de usuários', 'Treine os usuários finais da ferramenta.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['Treinamento de usuários.','E-mail: "4.2 Template Etapa 3 - Homologação (Formalização do Treinamento usuários)".']::text[], '{}', '{}', ARRAY['tpl-treinamento-usuarios']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('sm', 'go-live', 14, 'Go live', 'Formalize a entrada em produção do projeto.', 'gp', ARRAY['consultor','cliente']::text[], NULL, ARRAY['O go live é formalizado pelo GP, com o e-mail "5. Template etapa 4 - Go live".']::text[], '{}', '{}', ARRAY['tpl-go-live']::text[], '{}');

insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'recebimento', 1, 'Recebimento do projeto', 'O GP é notificado do início do projeto e responde ao cliente.', 'gp', '{}', '2 dias úteis', ARRAY['Somos notificados do início do projeto de duas formas: atribuição no ticket do HubSpot, e e-mail enviado pela gestão nos apresentando ao cliente.','No LE, é o GP quem responde o e-mail de apresentação dentro do SLA — diferente do SM, onde o consultor responde.']::text[], ARRAY['Verificar a atribuição do projeto no ticket do HubSpot','Responder o e-mail de apresentação dentro do SLA ("Boas Vindas - Projetos LE")']::text[], '{}', ARRAY['tpl-boas-vindas-le']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'analise-proposta', 2, 'Análise da proposta', 'O GP analisa a proposta comercial do projeto.', 'gp', '{}', NULL, ARRAY['O GP analisa a proposta comercial antes de qualquer alinhamento.']::text[], '{}', '{}', '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'alinhamento-interno', 3, 'Alinhamento interno com vendas', 'O GP alinha o histórico da venda com o time comercial.', 'gp', ARRAY['vendas']::text[], NULL, ARRAY['O GP efetua uma agenda de alinhamento interno com o time de vendas.']::text[], '{}', '{}', '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'alinhamento-inicial-cliente', 4, 'Alinhamento inicial com o cliente', 'Primeira conversa do GP com o cliente.', 'gp', ARRAY['cliente']::text[], NULL, ARRAY['O GP agenda um alinhamento inicial com o cliente.']::text[], '{}', '{}', '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'criacao-cronograma', 5, 'Criação do cronograma', 'O GP monta o cronograma do projeto no Smartsheet.', 'gp', '{}', NULL, ARRAY['O GP cria o cronograma do projeto.']::text[], '{}', ARRAY['Alterações de data e reprogramação de atividades no cronograma devem ser feitas pelo Gerente de Projetos, mesmo depois do handoff para o consultor.']::text[], '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'kick-off', 6, 'Kick-off', 'O GP conduz a reunião de abertura do projeto com o cliente.', 'gp', ARRAY['cliente','consultor']::text[], NULL, ARRAY['O GP conduz o kick off com o cliente.','Formalizar com o e-mail "Formalização do Kick Off - Projetos LE" (também referenciado como "2. Template Etapa 1 - Formalização - Kick-off" no fluxo padrão).']::text[], '{}', '{}', ARRAY['tpl-kickoff-le','tpl-kickoff-formalizacao']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'handoff-consultor', 7, 'Handoff para o consultor', 'A condução do projeto passa do GP para o consultor.', 'gp', ARRAY['consultor','cliente']::text[], NULL, ARRAY['Após a execução do kick off, o GP sinaliza ao consultor para que ele possa agendar a definição de escopo com o cliente e solicitar as cargas.','O consultor deve responder o e-mail no qual o GP apresenta o consultor ("Apresentação do Consultor LE"), propondo a agenda de definição de escopo.','Solicitar os requisitos de cada módulo contratado com os e-mails padrão correspondentes.','Criar uma pasta para o cliente no Drive, na pasta "Projetos L/E", onde devem ser armazenadas todas as cargas e documentações.']::text[], '{}', '{}', ARRAY['tpl-apresentacao-consultor-le','tpl-cargas-expense','tpl-requisitos-travel','tpl-implantacao-vcn','tpl-implantacao-cartao','tpl-carteira-digital']::text[], ARRAY['expense','travel','vcn','cartao-paytrack','carteira-digital']::text[]);
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'definicao-escopo', 8, 'Definição de escopo', 'O consultor registra o escopo e obtém o aceite do cliente.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['O consultor registra todo o escopo no Termo de escopo e o disponibiliza para aceite na base de produção do cliente.','E-mail a ser enviado ao cliente: "3. Template - Envio do Termo de escopo".']::text[], '{}', ARRAY['O aceite do escopo é obrigatório para seguir com a parametrização da base.']::text[], ARRAY['tpl-termo-escopo']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'parametrizacao', 9, 'Parametrização', 'Configuração da base conforme o escopo aceito.', 'consultor', '{}', NULL, ARRAY['Parametrização da base conforme o escopo aceito pelo cliente.']::text[], '{}', '{}', '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'apresentacao-ferramenta', 10, 'Apresentação da ferramenta', 'Apresentação da ferramenta parametrizada ao cliente.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['Apresentação da ferramenta já parametrizada ao cliente.']::text[], '{}', '{}', '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'homologacao-assistida', 11, 'Homologação assistida', 'Liberação do acesso para o cliente testar a base.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['Liberar o acesso à base para o cliente efetuar os testes.','E-mail: "4. Template Etapa 3 - Homologação".']::text[], '{}', '{}', ARRAY['tpl-homologacao']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'retorno-testes', 12, 'Retorno dos testes', 'Tratamento do retorno dos testes do cliente.', 'cliente', ARRAY['consultor']::text[], NULL, ARRAY['Retorno dos testes realizados pelo cliente na base homologada.']::text[], '{}', '{}', '{}', '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'aceite-homologacao', 13, 'Aceite da homologação', 'Aceite formal do Termo de homologação, obrigatório para o go live.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['O aceite do Termo de homologação é obrigatório para o go live do projeto.','E-mail: "2. Template Etapa 3 - Aceite da Homologação".']::text[], '{}', ARRAY['O aceite é obrigatório para o go live do projeto.']::text[], ARRAY['tpl-aceite-homologacao']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'treinamento-adm', 14, 'Treinamento de administrador', 'Treinamento do administrador da ferramenta.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['Treinamento de administrador.','E-mail: "4.1 Template Etapa 3 - Homologação (Treinamento ADM)".']::text[], '{}', '{}', ARRAY['tpl-treinamento-adm']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'treinamento-usuarios', 15, 'Treinamento de usuários', 'Treinamento dos usuários finais.', 'consultor', ARRAY['cliente']::text[], NULL, ARRAY['Treinamento de usuários.','E-mail: "4.2 Template Etapa 3 - Homologação (Formalização do Treinamento usuários)".']::text[], '{}', '{}', ARRAY['tpl-treinamento-usuarios']::text[], '{}');
insert into public.process_stages (segment, id, "order", title, short_description, owner, participants, sla, content, checklist, warnings, template_ids, module_ids) values ('le', 'go-live', 16, 'Go live', 'Formalização da entrada em produção do projeto.', 'gp', ARRAY['consultor','cliente']::text[], NULL, ARRAY['O go live é formalizado pelo GP, com o e-mail "5. Template etapa 4 - Go live".']::text[], '{}', '{}', ARRAY['tpl-go-live']::text[], '{}');

insert into public.process_templates (id, title, url) values ('tpl-primeiro-contato-sm', '1. Template - Etapas de projeto SM - primeiro contato', NULL);
insert into public.process_templates (id, title, url) values ('tpl-apresentacao-consultor-le', 'Apresentação do Consultor LE', NULL);
insert into public.process_templates (id, title, url) values ('tpl-cargas-expense', 'Solicitação de cargas do Expense', NULL);
insert into public.process_templates (id, title, url) values ('tpl-requisitos-travel', '[Projetos] Requisitos para implantação do Travel Tech', NULL);
insert into public.process_templates (id, title, url) values ('tpl-implantacao-vcn', '[Projetos] Passo 1. Implantação VCN', NULL);
insert into public.process_templates (id, title, url) values ('tpl-implantacao-cartao', 'Implantação Paytrack Card', NULL);
insert into public.process_templates (id, title, url) values ('tpl-carteira-digital', '[Projetos] Solicitação de documentos da Carteira Digital', NULL);
insert into public.process_templates (id, title, url) values ('tpl-kickoff-formalizacao', '2. Template Etapa 1 - Formalização - Kick-off', NULL);
insert into public.process_templates (id, title, url) values ('tpl-termo-escopo', '3. Template - Envio do Termo de escopo', NULL);
insert into public.process_templates (id, title, url) values ('tpl-homologacao', '4. Template Etapa 3 - Homologação', NULL);
insert into public.process_templates (id, title, url) values ('tpl-aceite-homologacao', '2. Template Etapa 3 - Aceite da Homologação', NULL);
insert into public.process_templates (id, title, url) values ('tpl-treinamento-adm', '4.1 Template Etapa 3 - Homologação (Treinamento ADM)', NULL);
insert into public.process_templates (id, title, url) values ('tpl-treinamento-usuarios', '4.2 Template Etapa 3 - Homologação (Formalização do Treinamento usuários)', NULL);
insert into public.process_templates (id, title, url) values ('tpl-go-live', '5. Template etapa 4 - Go live', NULL);
insert into public.process_templates (id, title, url) values ('tpl-status-report-atrasado', 'Status Report ATRASADO', NULL);
insert into public.process_templates (id, title, url) values ('tpl-status-report-reprogramado', 'Status Report - Cronograma Reprogramado', NULL);
insert into public.process_templates (id, title, url) values ('tpl-status-report-no-prazo', 'Status Report - Cronograma no PRAZO', NULL);
insert into public.process_templates (id, title, url) values ('tpl-boas-vindas-le', 'Boas Vindas - Projetos LE', NULL);
insert into public.process_templates (id, title, url) values ('tpl-kickoff-le', 'Formalização do Kick Off - Projetos LE', NULL);
insert into public.process_templates (id, title, url) values ('tpl-orientacao-conciliacao', '4.2 Template Etapa 3 - Orientação sobre conciliação de faturas', NULL);

insert into public.process_modules (id, title, content, template_ids) values ('expense', 'Expense', ARRAY['Solicitar as cargas iniciais do cliente com o e-mail padrão de solicitação de cargas.']::text[], ARRAY['tpl-cargas-expense']::text[]);
insert into public.process_modules (id, title, content, template_ids) values ('travel', 'Travel', ARRAY['Solicitar os requisitos com o e-mail padrão de implantação do Travel Tech.','No SM, o formulário de requisitos é enviado pelo HubSpot: selecionar o contato e preencher o "Papel do contato" (ex.: responsável pela implantação) e a "Data para disparo da pesquisa".','Se o projeto tiver Travel, é obrigatório manter uma observação atualizada no HubSpot com o status de: Contrato (enviado/assinado), Aditivo (se o cliente usa cartão de crédito — foto recebida e aditivo assinado), Forma de pagamento (por serviço) e Locação (se utiliza e como está o acordo tripartite).']::text[], ARRAY['tpl-requisitos-travel']::text[]);
insert into public.process_modules (id, title, content, template_ids) values ('vcn', 'VCN', ARRAY['Solicitar os requisitos com o e-mail padrão "Passo 1. Implantação VCN".']::text[], ARRAY['tpl-implantacao-vcn']::text[]);
insert into public.process_modules (id, title, content, template_ids) values ('cartao-paytrack', 'Cartão Paytrack', ARRAY['Solicitar os requisitos com o e-mail padrão de implantação do Paytrack Card.']::text[], ARRAY['tpl-implantacao-cartao']::text[]);
insert into public.process_modules (id, title, content, template_ids) values ('carteira-digital', 'Carteira Digital', ARRAY['Solicitar os documentos necessários com o e-mail padrão de solicitação de documentos da Carteira Digital.']::text[], ARRAY['tpl-carteira-digital']::text[]);
insert into public.process_modules (id, title, content, template_ids) values ('conciliacao', 'Conciliação', ARRAY['Módulo de conciliação, implantado seguindo o processo padrão do serviço contratado.']::text[], '{}');
insert into public.process_modules (id, title, content, template_ids) values ('integracoes', 'Integrações', ARRAY['Tipos de condução documentados: projeto novo com integração em primeira onda; projeto novo com integração em segunda onda; projeto de base.','Etapas internas: sprint, cronograma, reunião de briefing/alinhamento, reunião de escopo, levantamento de requisitos técnicos e alocação na sprint.']::text[], '{}');
